#include "StdAfx.h"
#include "SmartAttribute.h"

struct AttributeIdAndName attributeIdAndName[] =
{
	{1, "Raw_Read_Error_Rate"},
	{2, "Throughput_Performance"},
	{3, "Spin_Up_Time"},
	{4, "Start_Stop_Count"},
	{5, "Reallocated_Sector_Ct"},
	{6, "Read_Channel_Margin"},
	{7, "Seek_Error_Rate"},
	{8, "Seek_Time_Performance"},
	{9, "Power_On_Hours"},
	{10, "Spin_Retry_Count"},
	{11, "Calibration_Retry_Count"},
	{12, "Power_Cycle_Count"},
	{13, "Read_Soft_Error_Rate"},
	{175, "Program_Fail_Count_Chip"},
	{176, "Erase_Fail_Count_Chip"},
	{177, "Wear_Leveling_Count"},
	{178, "Used_Rsvd_Blk_Cnt_Chip"},
	{179, "Used_Rsvd_Blk_Cnt_Tot"},
	{180, "Unused_Rsvd_Blk_Cnt_Tot"},
	{181, "Program_Fail_Cnt_Total"},
	{182, "Erase_Fail_Count_Total"},
	{183, "Runtime_Bad_Block"},
	{184, "End-to-End_Error"},
	{187, "Reported_Uncorrect"},
	{188, "Command_Timeout"},
	{189, "High_Fly_Writes"},
	{190, "Airflow_Temperature_Cel"},
	{191, "G-Sense_Error_Rate"},
	{192, "Power-Off_Retract_Count"},
	{193, "Load_Cycle_Count"},
	{194, "Temperature_Celsius"},
	{195, "Hardware_ECC_Recovered"},
	{196, "Reallocated_Event_Count"},
	{197, "Current_Pending_Sector"},
	{198, "Offline_Uncorrectable"},
	{199, "UDMA_CRC_Error_Count"},
	{200, "Multi_Zone_Error_Rate"},
	{201, "Soft_Read_Error_Rate"},
	{202, "Data_Address_Mark_Errs"},
	{203, "Run_Out_Cancel"},
	{204, "Soft_ECC_Correction"},
	{205, "Thermal_Asperity_Rate"},
	{206, "Flying_Height"},
	{207, "Spin_High_Current"},
	{208, "Spin_Buzz"},
	{209, "Offline_Seek_Performnce"},
	{210, "Vibration_During_Write"},
	{211, "Vibration_During_Read"},
	{212, "Shock_During_Write"},
	{220, "Disk_Shift"},
	{221, "G-Sense_Error_Rate"},
	{222, "Loaded_Hours"},
	{223, "Load_Retry_Count"},
	{224, "Load_Friction"},
	{225, "Load_Cycle_Count"},
	{226, "Load-in_Time"},
	{227, "Torq-amp_Count"},
	{228, "Power-off_Retract_Count"},
	{230, "Head_Amplitude"},
	{231, "Temperature_Celsius"},
	{232, "Available_Reservd_Space"},
	{233, "Media_Wearout_Indicator"},
	{240, "Head_Flying_Hours"},
	{241, "Total_LBAs_Written"},
	{242, "Total_LBAs_Read"},
	{250, "Read_Error_Retry_Rate"},
	{254, "Free_Fall_Sensor"}
};

int GetSmartAttributeCount()
{
	return sizeof(attributeIdAndName)/sizeof(AttributeIdAndName);
}
